// Package v1 Code generated by swaggo/swag. DO NOT EDIT
package v1

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "post": {
                "description": "Create a new account",
                "produces": [
                    "application/json"
                ],
                "summary": "Create an account",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controllers_account.createAccountResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/bank_internal_controllers_httputils.HTTPError"
                        }
                    }
                }
            }
        },
        "/accounts/{accountID}/balance": {
            "get": {
                "description": "Retrieve the balance of an account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get account balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "accountID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controllers_account.getAccountBalanceResponseBody"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/bank_internal_controllers_httputils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/bank_internal_controllers_httputils.HTTPError"
                        }
                    }
                }
            }
        },
        "/accounts/{accountID}/transactions": {
            "post": {
                "description": "Perform a withdrawal transaction from the account",
                "consumes": [
                    "application/json"
                ],
                "summary": "Withdraw transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "accountID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Withdraw transaction request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controllers_account.withdrawTransactionRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/bank_internal_controllers_httputils.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/bank_internal_controllers_httputils.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bank_internal_controllers_httputils.HTTPError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_controllers_account.TransactionType": {
            "type": "string",
            "enum": [
                "deposit",
                "withdraw"
            ],
            "x-enum-varnames": [
                "DepositTransactionType",
                "WithdrawTransactionType"
            ]
        },
        "internal_controllers_account.createAccountResponseBody": {
            "type": "object",
            "properties": {
                "accountID": {
                    "type": "string"
                }
            }
        },
        "internal_controllers_account.depositTransactionRequestBody": {
            "type": "object",
            "properties": {
                "ammount": {
                    "type": "number"
                },
                "type": {
                    "$ref": "#/definitions/internal_controllers_account.TransactionType"
                }
            }
        },
        "internal_controllers_account.getAccountBalanceResponseBody": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                }
            }
        },
        "internal_controllers_account.withdrawTransactionRequestBody": {
            "type": "object",
            "properties": {
                "ammount": {
                    "type": "number"
                },
                "type": {
                    "$ref": "#/definitions/internal_controllers_account.TransactionType"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Bank",
	Description:      "Online Bank API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
